version: '3.9'
services:
  frontend:
    container_name: frontend
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8000:3000
    tty: true